//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountDetailType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="accountDetailType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IIN"/&gt;
 *     &lt;enumeration value="UIDNUM"/&gt;
 *     &lt;enumeration value="IFSC"/&gt;
 *     &lt;enumeration value="ACTYPE"/&gt;
 *     &lt;enumeration value="ACNUM"/&gt;
 *     &lt;enumeration value="MMID"/&gt;
 *     &lt;enumeration value="MOBNUM"/&gt;
 *     &lt;enumeration value="CARDNUM"/&gt;
 *     &lt;enumeration value="CREDIT"/&gt;
 *     &lt;enumeration value="PPIWALLET"/&gt;
 *     &lt;enumeration value="BANKWALLET"/&gt;
 *     &lt;enumeration value="SEMICLOSEDBANKWALLET"/&gt;
 *     &lt;enumeration value="SEMICLOSEDPPIWALLET"/&gt;
 *     &lt;enumeration value="NRO"/&gt;
 *     &lt;enumeration value="UIDTOKEN"/&gt;
 *     &lt;enumeration value="VID"/&gt;
 *     &lt;enumeration value="CIF"/&gt;
 *     &lt;enumeration value="REFKEY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "accountDetailType")
@XmlEnum
public enum AccountDetailType {

    IIN,
    UIDNUM,
    IFSC,
    ACTYPE,
    ACNUM,
    MMID,
    MOBNUM,
    CARDNUM,
    CREDIT,
    PPIWALLET,
    BANKWALLET,
    SEMICLOSEDBANKWALLET,
    SEMICLOSEDPPIWALLET,
    NRO,
    UIDTOKEN,
    VID,
    CIF,
    REFKEY;

    public String value() {
        return name();
    }

    public static AccountDetailType fromValue(String v) {
        return valueOf(v);
    }

}
