//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for credsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="credsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Cred" maxOccurs="10"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Data"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Auth" type="{http://npci.org/upi/schema/}Auth" minOccurs="0"/&gt;
 *                   &lt;element name="Otp" type="{http://npci.org/upi/schema/}Otp" minOccurs="0"/&gt;
 *                   &lt;element name="KycReqInfo" type="{http://npci.org/upi/schema/}KycReqInfo" minOccurs="0"/&gt;
 *                   &lt;element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" /&gt;
 *                 &lt;attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credsType", propOrder = {
    "cred"
})
public class CredsType {

    @XmlElement(name = "Cred", required = true)
    protected List<CredsType.Cred> cred;

    /**
     * Gets the value of the cred property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the cred property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCred().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredsType.Cred }
     *
     *
     */
    public List<CredsType.Cred> getCred() {
        if (cred == null) {
            cred = new ArrayList<>();
        }
        return this.cred;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Data"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Auth" type="{http://npci.org/upi/schema/}Auth" minOccurs="0"/&gt;
     *         &lt;element name="Otp" type="{http://npci.org/upi/schema/}Otp" minOccurs="0"/&gt;
     *         &lt;element name="KycReqInfo" type="{http://npci.org/upi/schema/}KycReqInfo" minOccurs="0"/&gt;
     *         &lt;element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" /&gt;
     *       &lt;attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "auth",
        "meta"
    })
    public static class Cred {

        @XmlElement(name = "Data", required = true)
        protected CredsType.Cred.Data data;
        @XmlElement(name = "Auth")
        protected Auth auth;
        @XmlElement(name = "Meta")
        protected MetaType meta;
        @XmlAttribute(name = "type", required = true)
        protected CredType type;
        @XmlAttribute(name = "subType", required = true)
        protected CredSubType subType;


        public Cred() {}

		public Cred(CredType type, CredSubType subType) {
			this.type = type;
			this.subType = subType;
		}



		/**
         * Gets the value of the data property.
         *
         * @return
         *     possible object is
         *     {@link CredsType.Cred.Data }
         *
         */
        public CredsType.Cred.Data getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         *
         * @param value
         *     allowed object is
         *     {@link CredsType.Cred.Data }
         *
         */
        public void setData(CredsType.Cred.Data value) {
            this.data = value;
        }

        /**
         * Gets the value of the auth property.
         *
         * @return
         *     possible object is
         *     {@link Auth }
         *
         */
        public Auth getAuth() {
            return auth;
        }

        /**
         * Sets the value of the auth property.
         *
         * @param value
         *     allowed object is
         *     {@link Auth }
         *
         */
        public void setAuth(Auth value) {
            this.auth = value;
        }

        /**
         * Gets the value of the meta property.
         *
         * @return
         *     possible object is
         *     {@link MetaType }
         *
         */
        public MetaType getMeta() {
            return meta;
        }

        /**
         * Sets the value of the meta property.
         *
         * @param value
         *     allowed object is
         *     {@link MetaType }
         *
         */
        public void setMeta(MetaType value) {
            this.meta = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return
         *     possible object is
         *     {@link CredType }
         *
         */
        public CredType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value
         *     allowed object is
         *     {@link CredType }
         *
         */
        public void setType(CredType value) {
            this.type = value;
        }

        /**
         * Gets the value of the subType property.
         *
         * @return
         *     possible object is
         *     {@link CredSubType }
         *
         */
        public CredSubType getSubType() {
            return subType;
        }

        /**
         * Sets the value of the subType property.
         *
         * @param value
         *     allowed object is
         *     {@link CredSubType }
         *
         */
        public void setSubType(CredSubType value) {
            this.subType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Data {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "ki")
            protected String ki;




            public Data() {}

			public Data(String value) {
				this.value = value;
			}



			/**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the code property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the ki property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getKi() {
                return ki;
            }

            /**
             * Sets the value of the ki property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setKi(String value) {
                this.ki = value;
            }

        }

    }

}
