//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credSubType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="credSubType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IIR"/&gt;
 *     &lt;enumeration value="FMR"/&gt;
 *     &lt;enumeration value="FIR"/&gt;
 *     &lt;enumeration value="OTP"/&gt;
 *     &lt;enumeration value="SMS"/&gt;
 *     &lt;enumeration value="EMAIL"/&gt;
 *     &lt;enumeration value="HOTP"/&gt;
 *     &lt;enumeration value="TOTP"/&gt;
 *     &lt;enumeration value="MPIN"/&gt;
 *     &lt;enumeration value="ATMPIN"/&gt;
 *     &lt;enumeration value="CVV1"/&gt;
 *     &lt;enumeration value="CVV2"/&gt;
 *     &lt;enumeration value="EMV"/&gt;
 *     &lt;enumeration value="initial"/&gt;
 *     &lt;enumeration value="reset"/&gt;
 *     &lt;enumeration value="rotate"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *     &lt;enumeration value="AADHAAR-BIO-FP"/&gt;
 *     &lt;enumeration value="AADHAAR-BIO-IRIS"/&gt;
 *     &lt;enumeration value="AADHAAR-BIO-OTP"/&gt;
 *     &lt;enumeration value="DS"/&gt;
 *     &lt;enumeration value="CARDDETAILS"/&gt;
 *     &lt;enumeration value="FACEAUTH"/&gt;
 *     &lt;enumeration value="UIDAI-AUTH-CODE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "credSubType")
@XmlEnum
public enum CredSubType {

    IIR("IIR"),
    FMR("FMR"),
    FIR("FIR"),
    OTP("OTP"),
    SMS("SMS"),
    EMAIL("EMAIL"),
    HOTP("HOTP"),
    TOTP("TOTP"),
    MPIN("MPIN"),
    ATMPIN("ATMPIN"),
    @XmlEnumValue("CVV1")
    CVV_1("CVV1"),
    @XmlEnumValue("CVV2")
    CVV_2("CVV2"),
    EMV("EMV"),
    @XmlEnumValue("initial")
    INITIAL("initial"),
    @XmlEnumValue("reset")
    RESET("reset"),
    @XmlEnumValue("rotate")
    ROTATE("rotate"),
    NA("NA"),
    @XmlEnumValue("AADHAAR-BIO-FP")
    AADHAAR_BIO_FP("AADHAAR-BIO-FP"),
    @XmlEnumValue("AADHAAR-BIO-IRIS")
    AADHAAR_BIO_IRIS("AADHAAR-BIO-IRIS"),
    @XmlEnumValue("AADHAAR-BIO-OTP")
    AADHAAR_BIO_OTP("AADHAAR-BIO-OTP"),
    DS("DS"),
    CARDDETAILS("CARDDETAILS"),
    FACEAUTH("FACEAUTH"),
    @XmlEnumValue("UIDAI-AUTH-CODE")
    UIDAI_AUTH_CODE("UIDAI-AUTH-CODE");
    private final String value;

    CredSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredSubType fromValue(String v) {
        for (CredSubType c: CredSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
