//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="credType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AADHAAR"/&gt;
 *     &lt;enumeration value="OTP"/&gt;
 *     &lt;enumeration value="PIN"/&gt;
 *     &lt;enumeration value="CARD"/&gt;
 *     &lt;enumeration value="PreApproved"/&gt;
 *     &lt;enumeration value="Challenge"/&gt;
 *     &lt;enumeration value="UPI-Mandate"/&gt;
 *     &lt;enumeration value="PostCredit"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "credType")
@XmlEnum
public enum CredType {

    AADHAAR("AADHAAR"),
    OTP("OTP"),
    PIN("PIN"),
    CARD("CARD"),
    @XmlEnumValue("PreApproved")
    PRE_APPROVED("PreApproved"),
    @XmlEnumValue("Challenge")
    CHALLENGE("Challenge"),
    @XmlEnumValue("UPI-Mandate")
    UPI_MANDATE("UPI-Mandate"),
    @XmlEnumValue("PostCredit")
    POST_CREDIT("PostCredit");
    private final String value;

    CredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredType fromValue(String v) {
        for (CredType c: CredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
