//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identityType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="identityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}identityConstant" /&gt;
 *       &lt;attribute name="verifiedName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identityType")
public class IdentityType {

    @XmlAttribute(name = "type", required = true)
    protected IdentityConstant type;
    @XmlAttribute(name = "verifiedName", required = true)
    protected String verifiedName;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link IdentityConstant }
     *
     */
    public IdentityConstant getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentityConstant }
     *
     */
    public void setType(IdentityConstant value) {
        this.type = value;
    }

    /**
     * Gets the value of the verifiedName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVerifiedName() {
        return verifiedName;
    }

    /**
     * Sets the value of the verifiedName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVerifiedName(String value) {
        this.verifiedName = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
