//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="infoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Identity" type="{http://npci.org/upi/schema/}identityType"/&gt;
 *         &lt;element name="Rating" type="{http://npci.org/upi/schema/}ratingType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoType", propOrder = {
    "identity",
    "rating"
})
public class InfoType {

    @XmlElement(name = "Identity", required = true)
    protected IdentityType identity;
    @XmlElement(name = "Rating")
    protected RatingType rating;

    /**
     * Gets the value of the identity property.
     *
     * @return
     *     possible object is
     *     {@link IdentityType }
     *
     */
    public IdentityType getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentityType }
     *
     */
    public void setIdentity(IdentityType value) {
        this.identity = value;
    }

    /**
     * Gets the value of the rating property.
     *
     * @return
     *     possible object is
     *     {@link RatingType }
     *
     */
    public RatingType getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     *
     * @param value
     *     allowed object is
     *     {@link RatingType }
     *
     */
    public void setRating(RatingType value) {
        this.rating = value;
    }

}
