//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetaType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MetaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="lk" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ac" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sa" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ver" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetaType")
public class MetaType {

    @XmlAttribute(name = "lk")
    protected String lk;
    @XmlAttribute(name = "ac")
    protected String ac;
    @XmlAttribute(name = "sa")
    protected String sa;
    @XmlAttribute(name = "uid")
    protected String uid;
    @XmlAttribute(name = "ver")
    protected String ver;

    /**
     * Gets the value of the lk property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLk() {
        return lk;
    }

    /**
     * Sets the value of the lk property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLk(String value) {
        this.lk = value;
    }

    /**
     * Gets the value of the ac property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAc(String value) {
        this.ac = value;
    }

    /**
     * Gets the value of the sa property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSa() {
        return sa;
    }

    /**
     * Sets the value of the sa property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSa(String value) {
        this.sa = value;
    }

    /**
     * Gets the value of the uid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the ver property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVer(String value) {
        this.ver = value;
    }

}
