//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Meta complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Meta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="udc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lov" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rdsId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rdsVer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dpId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meta", propOrder = {
    "udc",
    "lot",
    "lov",
    "rdsId",
    "rdsVer",
    "dpId",
    "dc",
    "mi",
    "mc"
})
public class Meta {

    @XmlElement(required = true)
    protected String udc;
    @XmlElement(required = true)
    protected String lot;
    @XmlElement(required = true)
    protected String lov;
    @XmlElement(required = true)
    protected String rdsId;
    @XmlElement(required = true)
    protected String rdsVer;
    @XmlElement(required = true)
    protected String dpId;
    @XmlElement(required = true)
    protected String dc;
    @XmlElement(required = true)
    protected String mi;
    @XmlElement(required = true)
    protected String mc;

    /**
     * Gets the value of the udc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUdc() {
        return udc;
    }

    /**
     * Sets the value of the udc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUdc(String value) {
        this.udc = value;
    }

    /**
     * Gets the value of the lot property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLot() {
        return lot;
    }

    /**
     * Sets the value of the lot property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLot(String value) {
        this.lot = value;
    }

    /**
     * Gets the value of the lov property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLov() {
        return lov;
    }

    /**
     * Sets the value of the lov property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLov(String value) {
        this.lov = value;
    }

    /**
     * Gets the value of the rdsId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRdsId() {
        return rdsId;
    }

    /**
     * Sets the value of the rdsId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRdsId(String value) {
        this.rdsId = value;
    }

    /**
     * Gets the value of the rdsVer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRdsVer() {
        return rdsVer;
    }

    /**
     * Sets the value of the rdsVer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRdsVer(String value) {
        this.rdsVer = value;
    }

    /**
     * Gets the value of the dpId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDpId() {
        return dpId;
    }

    /**
     * Sets the value of the dpId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDpId(String value) {
        this.dpId = value;
    }

    /**
     * Gets the value of the dc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDc() {
        return dc;
    }

    /**
     * Sets the value of the dc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDc(String value) {
        this.dc = value;
    }

    /**
     * Gets the value of the mi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMi() {
        return mi;
    }

    /**
     * Sets the value of the mi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMi(String value) {
        this.mi = value;
    }

    /**
     * Gets the value of the mc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMc() {
        return mc;
    }

    /**
     * Sets the value of the mc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMc(String value) {
        this.mc = value;
    }

}
