//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//

package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.fss.aeps.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: com.fss.aeps.jaxb
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link RespBalEnq }
	 *
	 */
	public RespBalEnq createRespBalEnq() {
		return new RespBalEnq();
	}

	/**
	 * Create an instance of {@link RespChkTxn }
	 *
	 */
	public RespChkTxn createRespChkTxn() {
		return new RespChkTxn();
	}

	/**
	 * Create an instance of {@link ReqPay }
	 *
	 */
	public ReqPay createReqPay() {
		return new ReqPay();
	}

	/**
	 * Create an instance of {@link RespPay }
	 *
	 */
	public RespPay createRespPay() {
		return new RespPay();
	}

	/**
	 * Create an instance of {@link CredsType }
	 *
	 */
	public CredsType createCredsType() {
		return new CredsType();
	}

	/**
	 * Create an instance of {@link CredsType.Cred }
	 *
	 */
	public CredsType.Cred createCredsTypeCred() {
		return new CredsType.Cred();
	}

	/**
	 * Create an instance of {@link AccountType }
	 *
	 */
	public AccountType createAccountType() {
		return new AccountType();
	}

	/**
	 * Create an instance of {@link DeviceType }
	 *
	 */
	public DeviceType createDeviceType() {
		return new DeviceType();
	}

	/**
	 * Create an instance of {@link AmountType }
	 *
	 */
	public AmountType createAmountType() {
		return new AmountType();
	}

	/**
	 * Create an instance of {@link RiskScoresType }
	 *
	 */
	public RiskScoresType createRiskScoresType() {
		return new RiskScoresType();
	}

	/**
	 * Create an instance of {@link RespBalEnq.Payer }
	 *
	 */
	public RespBalEnq.Payer createRespBalEnqPayer() {
		return new RespBalEnq.Payer();
	}

	/**
	 * Create an instance of {@link RespBalEnq.Payer.MiniStatement }
	 *
	 */
	public RespBalEnq.Payer.MiniStatement createRespBalEnqPayerMiniStatement() {
		return new RespBalEnq.Payer.MiniStatement();
	}

	/**
	 * Create an instance of {@link RespBalEnq.Payer.Bal }
	 *
	 */
	public RespBalEnq.Payer.Bal createRespBalEnqPayerBal() {
		return new RespBalEnq.Payer.Bal();
	}

	/**
	 * Create an instance of {@link HeadType }
	 *
	 */
	public HeadType createHeadType() {
		return new HeadType();
	}

	/**
	 * Create an instance of {@link Ack }
	 *
	 */
	public Ack createAck() {
		return new Ack();
	}

	/**
	 * Create an instance of {@link ErrorMessage }
	 *
	 */
	public ErrorMessage createErrorMessage() {
		return new ErrorMessage();
	}

	/**
	 * Create an instance of {@link ReqBalEnq }
	 *
	 */
	public ReqBalEnq createReqBalEnq() {
		return new ReqBalEnq();
	}

	/**
	 * Create an instance of {@link PayTrans }
	 *
	 */
	public PayTrans createPayTrans() {
		return new PayTrans();
	}

	/**
	 * Create an instance of {@link PayerType }
	 *
	 */
	public PayerType createPayerType() {
		return new PayerType();
	}

	/**
	 * Create an instance of {@link RespType }
	 *
	 */
	public RespType createRespType() {
		return new RespType();
	}

	/**
	 * Create an instance of {@link ReqBioAuth }
	 *
	 */
	public ReqBioAuth createReqBioAuth() {
		return new ReqBioAuth();
	}

	/**
	 * Create an instance of {@link RespBioAuth }
	 *
	 */
	public RespBioAuth createRespBioAuth() {
		return new RespBioAuth();
	}

	/**
	 * Create an instance of {@link UidaiData }
	 *
	 */
	public UidaiData createUidaiData() {
		return new UidaiData();
	}

	/**
	 * Create an instance of {@link ReqChkTxn }
	 *
	 */
	public ReqChkTxn createReqChkTxn() {
		return new ReqChkTxn();
	}

	/**
	 * Create an instance of {@link PayeeType }
	 *
	 */
	public PayeeType createPayeeType() {
		return new PayeeType();
	}

	/**
	 * Create an instance of {@link VerificationSequence }
	 *
	 */
	public VerificationSequence createVerificationSequence() {
		return new VerificationSequence();
	}

	/**
	 * Create an instance of {@link RespChkTxn.Resp }
	 *
	 */
	public RespChkTxn.Resp createRespChkTxnResp() {
		return new RespChkTxn.Resp();
	}

	/**
	 * Create an instance of {@link PayeesType }
	 *
	 */
	public PayeesType createPayeesType() {
		return new PayeesType();
	}

	/**
	 * Create an instance of {@link RespPay.Resp }
	 *
	 */
	public RespPay.Resp createRespPayResp() {
		return new RespPay.Resp();
	}

	/**
	 * Create an instance of {@link IdentityType }
	 *
	 */
	public IdentityType createIdentityType() {
		return new IdentityType();
	}

	/**
	 * Create an instance of {@link PayerInfoType }
	 *
	 */
	public PayerInfoType createPayerInfoType() {
		return new PayerInfoType();
	}

	/**
	 * Create an instance of {@link RatingType }
	 *
	 */
	public RatingType createRatingType() {
		return new RatingType();
	}

	/**
	 * Create an instance of {@link InfoType }
	 *
	 */
	public InfoType createInfoType() {
		return new InfoType();
	}

	/**
	 * Create an instance of {@link Ref }
	 *
	 */
	public Ref createRef() {
		return new Ref();
	}

	/**
	 * Create an instance of {@link MetaType }
	 *
	 */
	public MetaType createMetaType() {
		return new MetaType();
	}

	/**
	 * Create an instance of {@link Auth }
	 *
	 */
	public Auth createAuth() {
		return new Auth();
	}

	/**
	 * Create an instance of {@link Uses }
	 *
	 */
	public Uses createUses() {
		return new Uses();
	}

	/**
	 * Create an instance of {@link com.fss.aeps.jaxb.Meta }
	 *
	 */
	public com.fss.aeps.jaxb.Meta createMeta() {
		return new com.fss.aeps.jaxb.Meta();
	}

	/**
	 * Create an instance of {@link Skey }
	 *
	 */
	public Skey createSkey() {
		return new Skey();
	}

	/**
	 * Create an instance of {@link Hmac }
	 *
	 */
	public Hmac createHmac() {
		return new Hmac();
	}

	/**
	 * Create an instance of {@link com.fss.aeps.jaxb.Data }
	 *
	 */
	public com.fss.aeps.jaxb.Data createData() {
		return new com.fss.aeps.jaxb.Data();
	}

	/**
	 * Create an instance of {@link CredsType.Cred.Data }
	 *
	 */
	public CredsType.Cred.Data createCredsTypeCredData() {
		return new CredsType.Cred.Data();
	}

	/**
	 * Create an instance of {@link AccountType.Detail }
	 *
	 */
	public AccountType.Detail createAccountTypeDetail() {
		return new AccountType.Detail();
	}

	/**
	 * Create an instance of {@link DeviceType.Tag }
	 *
	 */
	public DeviceType.Tag createDeviceTypeTag() {
		return new DeviceType.Tag();
	}

	/**
	 * Create an instance of {@link AmountType.Split }
	 *
	 */
	public AmountType.Split createAmountTypeSplit() {
		return new AmountType.Split();
	}

	/**
	 * Create an instance of {@link RiskScoresType.Score }
	 *
	 */
	public RiskScoresType.Score createRiskScoresTypeScore() {
		return new RiskScoresType.Score();
	}

	/**
	 * Create an instance of {@link RespBalEnq.Payer.MiniStatement.StmtData }
	 *
	 */
	public RespBalEnq.Payer.MiniStatement.StmtData createRespBalEnqPayerMiniStatementStmtData() {
		return new RespBalEnq.Payer.MiniStatement.StmtData();
	}

	/**
	 * Create an instance of {@link RespBalEnq.Payer.Bal.Data }
	 *
	 */
	public RespBalEnq.Payer.Bal.Data createRespBalEnqPayerBalData() {
		return new RespBalEnq.Payer.Bal.Data();
	}

	/**
	 * Create an instance of {@link HeadType.Iso8583Element }
	 *
	 */
	public HeadType.Iso8583Element createHeadTypeIso8583Element() {
		return new HeadType.Iso8583Element();
	}

}
