//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://npci.org/upi/schema/")
package com.fss.aeps.jaxb;
