//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for payConstant.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="payConstant"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PAY"/&gt;
 *     &lt;enumeration value="COLLECT"/&gt;
 *     &lt;enumeration value="REVERSAL"/&gt;
 *     &lt;enumeration value="REFUND"/&gt;
 *     &lt;enumeration value="CREDIT"/&gt;
 *     &lt;enumeration value="DEBIT"/&gt;
 *     &lt;enumeration value="BAL"/&gt;
 *     &lt;enumeration value="ListPsp"/&gt;
 *     &lt;enumeration value="ListAccPvd"/&gt;
 *     &lt;enumeration value="ListKeys"/&gt;
 *     &lt;enumeration value="GetToken"/&gt;
 *     &lt;enumeration value="ListAccount"/&gt;
 *     &lt;enumeration value="ListVae"/&gt;
 *     &lt;enumeration value="ManageVae"/&gt;
 *     &lt;enumeration value="ValAdd"/&gt;
 *     &lt;enumeration value="SetCre"/&gt;
 *     &lt;enumeration value="ReqRegMob"/&gt;
 *     &lt;enumeration value="ResetRegMob"/&gt;
 *     &lt;enumeration value="ChkTxn"/&gt;
 *     &lt;enumeration value="Otp"/&gt;
 *     &lt;enumeration value="BalEnq"/&gt;
 *     &lt;enumeration value="Hbt"/&gt;
 *     &lt;enumeration value="PendingMsg"/&gt;
 *     &lt;enumeration value="TxnConfirmation"/&gt;
 *     &lt;enumeration value="CREATE"/&gt;
 *     &lt;enumeration value="REVOKE"/&gt;
 *     &lt;enumeration value="UPDATE"/&gt;
 *     &lt;enumeration value="ListPSPKeys"/&gt;
 *     &lt;enumeration value="BalChk"/&gt;
 *     &lt;enumeration value="ReqActivation"/&gt;
 *     &lt;enumeration value="International"/&gt;
 *     &lt;enumeration value="UPI Services"/&gt;
 *     &lt;enumeration value="IntlQr"/&gt;
 *     &lt;enumeration value="QrVal"/&gt;
 *     &lt;enumeration value="ReqFxRate"/&gt;
 *     &lt;enumeration value="RespFxRate"/&gt;
 *     &lt;enumeration value="Booking"/&gt;
 *     &lt;enumeration value="ValCust"/&gt;
 *     &lt;enumeration value="ReqMapperConfirmation"/&gt;
 *     &lt;enumeration value="MandateNotification"/&gt;
 *     &lt;enumeration value="FETCH"/&gt;
 *     &lt;enumeration value="RespKyc"/&gt;
 *     &lt;enumeration value="ReqKyc"/&gt;
 *     &lt;enumeration value="AUTH"/&gt;
 *     &lt;enumeration value="PAUSE"/&gt;
 *     &lt;enumeration value="UNPAUSE"/&gt;
 *     &lt;enumeration value="VR"/&gt;
 *     &lt;enumeration value="ChkBankStatus"/&gt;
 *     &lt;enumeration value="NameEnq"/&gt;
 *     &lt;enumeration value="MiniStmt"/&gt;
 *     &lt;enumeration value="BFD"/&gt;
 *     &lt;enumeration value="BIO-AUTH"/&gt;
 *     &lt;enumeration value="DEMO-AUTH"/&gt;
 *     &lt;enumeration value="REQ-OTP"/&gt;
 *     &lt;enumeration value="ADVICE"/&gt;
 *     &lt;enumeration value="OTP-AUTH-UPDATE"/&gt;
 *     &lt;enumeration value="EKYC"/&gt;
 *     &lt;enumeration value="TKN"/&gt;
 *     &lt;enumeration value="PAUSE"/&gt;
 *     &lt;enumeration value="UNPAUSE"/&gt;
 *     &lt;enumeration value="COMPLAINT"/&gt;
 *     &lt;enumeration value="DISPUTE"/&gt;
 *     &lt;enumeration value="STATUSUPDATE"/&gt;
 *     &lt;enumeration value="CHKSTATUS"/&gt;
 *     &lt;enumeration value="STATUS"/&gt;
 *     &lt;enumeration value="AUTOUPDATE"/&gt;
 *     &lt;enumeration value="BACKOFFICE"/&gt;
 *     &lt;enumeration value="ITD"/&gt;
 *     &lt;enumeration value="CMREGISTRATION"/&gt;
 *     &lt;enumeration value="CHECK"/&gt;
 *     &lt;enumeration value="HISTORY"/&gt;
 *     &lt;enumeration value="SHG"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "payConstant")
@XmlEnum
public enum PayConstant {

    PAY("PAY"),
    COLLECT("COLLECT"),
    REVERSAL("REVERSAL"),
    REFUND("REFUND"),
    CREDIT("CREDIT"),
    DEBIT("DEBIT"),
    BAL("BAL"),
    @XmlEnumValue("ListPsp")
    LIST_PSP("ListPsp"),
    @XmlEnumValue("ListAccPvd")
    LIST_ACC_PVD("ListAccPvd"),
    @XmlEnumValue("ListKeys")
    LIST_KEYS("ListKeys"),
    @XmlEnumValue("GetToken")
    GET_TOKEN("GetToken"),
    @XmlEnumValue("ListAccount")
    LIST_ACCOUNT("ListAccount"),
    @XmlEnumValue("ListVae")
    LIST_VAE("ListVae"),
    @XmlEnumValue("ManageVae")
    MANAGE_VAE("ManageVae"),
    @XmlEnumValue("ValAdd")
    VAL_ADD("ValAdd"),
    @XmlEnumValue("SetCre")
    SET_CRE("SetCre"),
    @XmlEnumValue("ReqRegMob")
    REQ_REG_MOB("ReqRegMob"),
    @XmlEnumValue("ResetRegMob")
    RESET_REG_MOB("ResetRegMob"),
    @XmlEnumValue("ChkTxn")
    CHK_TXN("ChkTxn"),
    @XmlEnumValue("Otp")
    OTP("Otp"),
    @XmlEnumValue("BalEnq")
    BAL_ENQ("BalEnq"),
    @XmlEnumValue("Hbt")
    HBT("Hbt"),
    @XmlEnumValue("PendingMsg")
    PENDING_MSG("PendingMsg"),
    @XmlEnumValue("TxnConfirmation")
    TXN_CONFIRMATION("TxnConfirmation"),
    CREATE("CREATE"),
    REVOKE("REVOKE"),
    UPDATE("UPDATE"),
    @XmlEnumValue("ListPSPKeys")
    LIST_PSP_KEYS("ListPSPKeys"),
    @XmlEnumValue("BalChk")
    BAL_CHK("BalChk"),
    @XmlEnumValue("ReqActivation")
    REQ_ACTIVATION("ReqActivation"),
    @XmlEnumValue("International")
    INTERNATIONAL("International"),
    @XmlEnumValue("UPI Services")
    UPI_SERVICES("UPI Services"),
    @XmlEnumValue("IntlQr")
    INTL_QR("IntlQr"),
    @XmlEnumValue("QrVal")
    QR_VAL("QrVal"),
    @XmlEnumValue("ReqFxRate")
    REQ_FX_RATE("ReqFxRate"),
    @XmlEnumValue("RespFxRate")
    RESP_FX_RATE("RespFxRate"),
    @XmlEnumValue("Booking")
    BOOKING("Booking"),
    @XmlEnumValue("ValCust")
    VAL_CUST("ValCust"),
    @XmlEnumValue("ReqMapperConfirmation")
    REQ_MAPPER_CONFIRMATION("ReqMapperConfirmation"),
    @XmlEnumValue("MandateNotification")
    MANDATE_NOTIFICATION("MandateNotification"),
    FETCH("FETCH"),
    @XmlEnumValue("RespKyc")
    RESP_KYC("RespKyc"),
    @XmlEnumValue("ReqKyc")
    REQ_KYC("ReqKyc"),
    AUTH("AUTH"),
    PAUSE("PAUSE"),
    UNPAUSE("UNPAUSE"),
    VR("VR"),
    @XmlEnumValue("ChkBankStatus")
    CHK_BANK_STATUS("ChkBankStatus"),
    @XmlEnumValue("NameEnq")
    NAME_ENQ("NameEnq"),
    @XmlEnumValue("MiniStmt")
    MINI_STMT("MiniStmt"),
    BFD("BFD"),
    @XmlEnumValue("BIO-AUTH")
    BIO_AUTH("BIO-AUTH"),
    @XmlEnumValue("DEMO-AUTH")
    DEMO_AUTH("DEMO-AUTH"),
    @XmlEnumValue("REQ-OTP")
    REQ_OTP("REQ-OTP"),
    ADVICE("ADVICE"),
    @XmlEnumValue("OTP-AUTH-UPDATE")
    OTP_AUTH_UPDATE("OTP-AUTH-UPDATE"),
    EKYC("EKYC"),
    TKN("TKN"),
    COMPLAINT("COMPLAINT"),
    DISPUTE("DISPUTE"),
    STATUSUPDATE("STATUSUPDATE"),
    CHKSTATUS("CHKSTATUS"),
    STATUS("STATUS"),
    AUTOUPDATE("AUTOUPDATE"),
    BACKOFFICE("BACKOFFICE"),
    ITD("ITD"),
    CMREGISTRATION("CMREGISTRATION"),
    CHECK("CHECK"),
    HISTORY("HISTORY"),
    SHG("SHG");
    private final String value;

    PayConstant(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PayConstant fromValue(String v) {
        for (PayConstant c: PayConstant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
