//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import java.math.BigDecimal;

import com.fss.aeps.jaxb.adapter.JaxbBigDecimalAdapter;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ref complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ref"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}refType" /&gt;
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="settAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="settCurrency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="respCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="regName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="reversalRespCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orgAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="acNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IFSC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="actn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="accType" type="{http://npci.org/upi/schema/}listedAccountType" /&gt;
 *       &lt;attribute name="opType" type="{http://npci.org/upi/schema/}payConstant" /&gt;
 *       &lt;attribute name="iin" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="respMsg" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bankName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="linkStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lastUpdTs" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="balAmt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="procStatus" type="{http://npci.org/upi/schema/}refProcStatus" /&gt;
 *       &lt;attribute name="adjAmt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adjTs" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adjRefId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adjFlag" type="{http://npci.org/upi/schema/}adjFlagType" /&gt;
 *       &lt;attribute name="adjCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adjRemarks" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rejReason" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cmId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ref")
public class Ref {

    @XmlAttribute(name = "type")
    protected RefType type;
    @XmlAttribute(name = "seqNum")
    protected String seqNum;
    @XmlAttribute(name = "addr")
    protected String addr;
    @XmlJavaTypeAdapter(JaxbBigDecimalAdapter.class)
    @XmlAttribute(name = "settAmount")
    protected BigDecimal settAmount;
    @XmlAttribute(name = "settCurrency")
    protected String settCurrency;
    @XmlAttribute(name = "approvalNum")
    protected String approvalNum;
    @XmlAttribute(name = "respCode")
    protected String respCode;
    @XmlAttribute(name = "regName")
    protected String regName;
    @XmlAttribute(name = "reversalRespCode")
    protected String reversalRespCode;
    @XmlJavaTypeAdapter(JaxbBigDecimalAdapter.class)
    @XmlAttribute(name = "orgAmount")
    protected BigDecimal orgAmount;
    @XmlAttribute(name = "acNum")
    protected String acNum;
    @XmlAttribute(name = "IFSC")
    protected String ifsc;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "actn")
    protected String actn;
    @XmlAttribute(name = "opType")
    protected PayConstant opType;
    @XmlAttribute(name = "iin")
    protected String iin;
    @XmlAttribute(name = "respMsg")
    protected String respMsg;
    @XmlAttribute(name = "bankName")
    protected String bankName;
    @XmlAttribute(name = "linkStatus")
    protected String linkStatus;
    @XmlAttribute(name = "lastUpdTs")
    protected String lastUpdTs;
    @XmlAttribute(name = "balAmt")
    protected String balAmt;
    @XmlAttribute(name = "adjAmt")
    protected String adjAmt;
    @XmlAttribute(name = "adjTs")
    protected String adjTs;
    @XmlAttribute(name = "adjRefId")
    protected String adjRefId;
    @XmlAttribute(name = "adjCode")
    protected String adjCode;
    @XmlAttribute(name = "adjRemarks")
    protected String adjRemarks;
    @XmlAttribute(name = "rejReason")
    protected String rejReason;
    @XmlAttribute(name = "cmId")
    protected String cmId;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link RefType }
     *
     */
    public RefType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link RefType }
     *
     */
    public void setType(RefType value) {
        this.type = value;
    }

    /**
     * Gets the value of the seqNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the addr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the settAmount property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public BigDecimal getSettAmount() {
        return settAmount;
    }

    /**
     * Sets the value of the settAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSettAmount(BigDecimal value) {
        this.settAmount = value;
    }

    /**
     * Gets the value of the settCurrency property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSettCurrency() {
        return settCurrency;
    }

    /**
     * Sets the value of the settCurrency property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSettCurrency(String value) {
        this.settCurrency = value;
    }

    /**
     * Gets the value of the approvalNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApprovalNum() {
        return approvalNum;
    }

    /**
     * Sets the value of the approvalNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApprovalNum(String value) {
        this.approvalNum = value;
    }

    /**
     * Gets the value of the respCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the regName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRegName() {
        return regName;
    }

    /**
     * Sets the value of the regName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegName(String value) {
        this.regName = value;
    }

    /**
     * Gets the value of the reversalRespCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReversalRespCode() {
        return reversalRespCode;
    }

    /**
     * Sets the value of the reversalRespCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReversalRespCode(String value) {
        this.reversalRespCode = value;
    }

    /**
     * Gets the value of the orgAmount property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public BigDecimal getOrgAmount() {
        return orgAmount;
    }

    /**
     * Sets the value of the orgAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrgAmount(BigDecimal value) {
        this.orgAmount = value;
    }

    /**
     * Gets the value of the acNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcNum() {
        return acNum;
    }

    /**
     * Sets the value of the acNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcNum(String value) {
        this.acNum = value;
    }

    /**
     * Gets the value of the ifsc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIFSC() {
        return ifsc;
    }

    /**
     * Sets the value of the ifsc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIFSC(String value) {
        this.ifsc = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the actn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActn() {
        return actn;
    }

    /**
     * Sets the value of the actn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActn(String value) {
        this.actn = value;
    }


    /**
     * Gets the value of the opType property.
     *
     * @return
     *     possible object is
     *     {@link PayConstant }
     *
     */
    public PayConstant getOpType() {
        return opType;
    }

    /**
     * Sets the value of the opType property.
     *
     * @param value
     *     allowed object is
     *     {@link PayConstant }
     *
     */
    public void setOpType(PayConstant value) {
        this.opType = value;
    }

    /**
     * Gets the value of the iin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIin() {
        return iin;
    }

    /**
     * Sets the value of the iin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIin(String value) {
        this.iin = value;
    }

    /**
     * Gets the value of the respMsg property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * Sets the value of the respMsg property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRespMsg(String value) {
        this.respMsg = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the linkStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLinkStatus() {
        return linkStatus;
    }

    /**
     * Sets the value of the linkStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLinkStatus(String value) {
        this.linkStatus = value;
    }

    /**
     * Gets the value of the lastUpdTs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastUpdTs() {
        return lastUpdTs;
    }

    /**
     * Sets the value of the lastUpdTs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastUpdTs(String value) {
        this.lastUpdTs = value;
    }

    /**
     * Gets the value of the balAmt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBalAmt() {
        return balAmt;
    }

    /**
     * Sets the value of the balAmt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBalAmt(String value) {
        this.balAmt = value;
    }


    /**
     * Gets the value of the adjAmt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdjAmt() {
        return adjAmt;
    }

    /**
     * Sets the value of the adjAmt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdjAmt(String value) {
        this.adjAmt = value;
    }

    /**
     * Gets the value of the adjTs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdjTs() {
        return adjTs;
    }

    /**
     * Sets the value of the adjTs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdjTs(String value) {
        this.adjTs = value;
    }

    /**
     * Gets the value of the adjRefId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdjRefId() {
        return adjRefId;
    }

    /**
     * Sets the value of the adjRefId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdjRefId(String value) {
        this.adjRefId = value;
    }


    /**
     * Gets the value of the adjCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdjCode() {
        return adjCode;
    }

    /**
     * Sets the value of the adjCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdjCode(String value) {
        this.adjCode = value;
    }

    /**
     * Gets the value of the adjRemarks property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdjRemarks() {
        return adjRemarks;
    }

    /**
     * Sets the value of the adjRemarks property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdjRemarks(String value) {
        this.adjRemarks = value;
    }

    /**
     * Gets the value of the rejReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRejReason() {
        return rejReason;
    }

    /**
     * Sets the value of the rejReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRejReason(String value) {
        this.rejReason = value;
    }

    /**
     * Gets the value of the cmId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCmId() {
        return cmId;
    }

    /**
     * Sets the value of the cmId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCmId(String value) {
        this.cmId = value;
    }

}
