//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fss.aeps.jaxb.adapter.IPayTrans;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://npci.org/upi/schema/}headType"/&gt;
 *         &lt;element name="Txn" type="{http://npci.org/upi/schema/}payTrans"/&gt;
 *         &lt;element name="Payer" type="{http://npci.org/upi/schema/}payerType"/&gt;
 *         &lt;element name="Payee" type="{http://npci.org/upi/schema/}payeeType"/&gt;
 *         &lt;element name="VerificationSequence" type="{http://npci.org/upi/schema/}VerificationSequence" maxOccurs="10" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "txn",
    "payer",
    "payee",
    "verificationSequence"
})
@XmlRootElement(name = "ReqChkTxn")
public class ReqChkTxn implements IPayTrans {

	@XmlTransient
	public final Map<String, Object>  context = new HashMap<>();

    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Txn", required = true)
    protected PayTrans txn;
    @XmlElement(name = "Payer", required = true)
    protected PayerType payer;
    @XmlElement(name = "Payee", required = true)
    protected PayeeType payee;
    @XmlElement(name = "VerificationSequence")
    protected List<VerificationSequence> verificationSequence;

    /**
     * Gets the value of the head property.
     *
     * @return
     *     possible object is
     *     {@link HeadType }
     *
     */
    @Override
	public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     *
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *
     */
    @Override
	public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the txn property.
     *
     * @return
     *     possible object is
     *     {@link PayTrans }
     *
     */
    @Override
	public PayTrans getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     *
     * @param value
     *     allowed object is
     *     {@link PayTrans }
     *
     */
    @Override
	public void setTxn(PayTrans value) {
        this.txn = value;
    }

    /**
     * Gets the value of the payer property.
     *
     * @return
     *     possible object is
     *     {@link PayerType }
     *
     */
    @Override
	public PayerType getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     *
     * @param value
     *     allowed object is
     *     {@link PayerType }
     *
     */
    @Override
	public void setPayer(PayerType value) {
        this.payer = value;
    }

    /**
     * Gets the value of the payee property.
     *
     * @return
     *     possible object is
     *     {@link PayeeType }
     *
     */
    public PayeeType getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     *
     * @param value
     *     allowed object is
     *     {@link PayeeType }
     *
     */
    public void setPayee(PayeeType value) {
        this.payee = value;
    }

    /**
     * Gets the value of the verificationSequence property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the verificationSequence property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerificationSequence().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationSequence }
     *
     *
     */
    public List<VerificationSequence> getVerificationSequence() {
        if (verificationSequence == null) {
            verificationSequence = new ArrayList<>();
        }
        return this.verificationSequence;
    }

}
