//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for respType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="respType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ref" type="{http://npci.org/upi/schema/}ref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PayerInfo" type="{http://npci.org/upi/schema/}payerInfoType" minOccurs="0"/&gt;
 *         &lt;element name="RegIdDetails" type="{http://npci.org/upi/schema/}regIdDetailsType" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="errCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="errDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="actn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="securePinUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="authCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "respType", propOrder = {
    "ref",
    "payerInfo"
})
public class RespType {

    @XmlElement(name = "Ref")
    protected List<Ref> ref;
    @XmlElement(name = "PayerInfo")
    protected PayerInfoType payerInfo;
    @XmlAttribute(name = "reqMsgId")
    protected String reqMsgId;
    @XmlAttribute(name = "result")
    protected ResultType result;
    @XmlAttribute(name = "errCode")
    protected String errCode;
    @XmlAttribute(name = "errDesc")
    protected String errDesc;
    @XmlAttribute(name = "actn")
    protected String actn;
    @XmlAttribute(name = "securePinUrl")
    protected String securePinUrl;
    @XmlAttribute(name = "authCode")
    protected String authCode;

    /**
     * Gets the value of the ref property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the ref property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ref }
     *
     *
     */
    public List<Ref> getRef() {
        if (ref == null) {
            ref = new ArrayList<>();
        }
        return this.ref;
    }

    /**
     * Gets the value of the payerInfo property.
     *
     * @return
     *     possible object is
     *     {@link PayerInfoType }
     *
     */
    public PayerInfoType getPayerInfo() {
        return payerInfo;
    }

    /**
     * Sets the value of the payerInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link PayerInfoType }
     *
     */
    public void setPayerInfo(PayerInfoType value) {
        this.payerInfo = value;
    }


    /**
     * Gets the value of the reqMsgId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReqMsgId() {
        return reqMsgId;
    }

    /**
     * Sets the value of the reqMsgId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReqMsgId(String value) {
        this.reqMsgId = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public ResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResult(ResultType value) {
        this.result = value;
    }

    /**
     * Gets the value of the errCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrCode(String value) {
        this.errCode = value;
    }

    /**
     * Gets the value of the errDesc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrDesc() {
        return errDesc;
    }

    /**
     * Sets the value of the errDesc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrDesc(String value) {
        this.errDesc = value;
    }

    /**
     * Gets the value of the actn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActn() {
        return actn;
    }

    /**
     * Sets the value of the actn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActn(String value) {
        this.actn = value;
    }

    /**
     * Gets the value of the securePinUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSecurePinUrl() {
        return securePinUrl;
    }

    /**
     * Sets the value of the securePinUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSecurePinUrl(String value) {
        this.securePinUrl = value;
    }

    /**
     * Gets the value of the authCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

}
