//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnSubType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="txnSubType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PAY"/&gt;
 *     &lt;enumeration value="COLLECT"/&gt;
 *     &lt;enumeration value="DEBIT"/&gt;
 *     &lt;enumeration value="CREDIT"/&gt;
 *     &lt;enumeration value="REFUND"/&gt;
 *     &lt;enumeration value="REVERSAL"/&gt;
 *     &lt;enumeration value="MANDATE"/&gt;
 *     &lt;enumeration value="CREATE"/&gt;
 *     &lt;enumeration value="UPDATE"/&gt;
 *     &lt;enumeration value="REVOKE"/&gt;
 *     &lt;enumeration value="PAUSE"/&gt;
 *     &lt;enumeration value="UNPAUSE"/&gt;
 *     &lt;enumeration value="TXN"/&gt;
 *     &lt;enumeration value="DISPUTE"/&gt;
 *     &lt;enumeration value="TXNDISPUTE"/&gt;
 *     &lt;enumeration value="PAYER"/&gt;
 *     &lt;enumeration value="PAYEE"/&gt;
 *     &lt;enumeration value="REMITTER"/&gt;
 *     &lt;enumeration value="BENEFICIARY"/&gt;
 *     &lt;enumeration value="DISPUTEHIST"/&gt;
 *     &lt;enumeration value="BANK-UIDAI"/&gt;
 *     &lt;enumeration value="BANK"/&gt;
 *     &lt;enumeration value="UIDAI"/&gt;
 *     &lt;enumeration value="PANAADHAAR"/&gt;
 *     &lt;enumeration value="ADVICE"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="VPA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "txnSubType")
@XmlEnum
public enum TxnSubType {

    PAY("PAY"),
    COLLECT("COLLECT"),
    DEBIT("DEBIT"),
    CREDIT("CREDIT"),
    REFUND("REFUND"),
    REVERSAL("REVERSAL"),
    MANDATE("MANDATE"),
    CREATE("CREATE"),
    UPDATE("UPDATE"),
    REVOKE("REVOKE"),
    PAUSE("PAUSE"),
    UNPAUSE("UNPAUSE"),
    TXN("TXN"),
    DISPUTE("DISPUTE"),
    TXNDISPUTE("TXNDISPUTE"),
    PAYER("PAYER"),
    PAYEE("PAYEE"),
    REMITTER("REMITTER"),
    BENEFICIARY("BENEFICIARY"),
    DISPUTEHIST("DISPUTEHIST"),
    @XmlEnumValue("BANK-UIDAI")
    BANK_UIDAI("BANK-UIDAI"),
    BANK("BANK"),
    UIDAI("UIDAI"),
    PANAADHAAR("PANAADHAAR"),
    ADVICE("ADVICE"),
    ID("ID"),
    VPA("VPA");
    private final String value;

    TxnSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TxnSubType fromValue(String v) {
        for (TxnSubType c: TxnSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
