//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.10 at 04:24:59 PM IST
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="txnType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CWD"/&gt;
 *     &lt;enumeration value="CD"/&gt;
 *     &lt;enumeration value="RTGS"/&gt;
 *     &lt;enumeration value="NEFT"/&gt;
 *     &lt;enumeration value="UPI"/&gt;
 *     &lt;enumeration value="IMPS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "txnType")
@XmlEnum
public enum TxnType {

    CWD,
    CD,
    RTGS,
    NEFT,
    UPI,
    IMPS;

    public String value() {
        return name();
    }

    public static TxnType fromValue(String v) {
        return valueOf(v);
    }

}
